### ISSUE TITLE
Parser fails quietly with an @id with no scheme

### ISSUE THREAD

**Issue by martinPikeGB** [filip26/titanium-json-ld#145]
```json
{
  "@id" : "x.y.z",
  "x:item" : {
    "@value" : "A_Token",
    "@type" : "http://www.w3.org/2001/XMLSchema#token"
  }
}
```

The above json-ld has an id with a relative (not absolute) URI.
The parser processes this as input without error but emits 
no Triples output.
Code:
```java
  try {
      JsonDocument doc = JsonDocument.of(stream);
      ToRdfApi tt = JsonLd.toRdf(doc);
      RdfDataset rdf = tt.get();   
      List<RdfNQuad> list = rdf.toList();
      ....
    } catch (JsonLdError e) {
    ....
    }
```
The list is empty.

I believe that the parser should either:
- process the id as-is
- signal an error in the input format. 

NOTE: Change the @id to 'urn:x.y.z' and it works fine.

**Comment by martinPikeGB** [comment]
In fact, other forms of invalid URI produce the same effect.

**Comment by filip26** [comment]
Hi,
the issue is that `x.y.z` is relative and document Url is not set. `toRdf` sees `x.y.z` as non well-formed subject and silently skips - see  the spec. [step 1.3.1](https://www.w3.org/TR/json-ld11-api/#algorithm-12).

Try set document Url manually e.g. ` doc.setDocumentUrl(URI.create("https://apicatog.com"));`

```java
  try {
      JsonDocument doc = JsonDocument.of(stream);
      doc.setDocumentUrl(URI.create("https://apicatog.com"));

      ToRdfApi tt = JsonLd.toRdf(doc);
      RdfDataset rdf = tt.get();   
      List<RdfNQuad> list = rdf.toList();
      ....
    } catch (JsonLdError e) {
    ....
    }
```

result:
```
<https://apicatog.com/x.y.z> <x:item> "A_Token"^^<http://www.w3.org/2001/XMLSchema#token> .
```
Version `1.0.3` will print warning that document Url is not set.
