### ISSUE TITLE
Question: disabling remote context loading

### ISSUE THREAD

**Issue by acoburn** [filip26/titanium-json-ld#45]
While it is clearly part of the JSON-LD specification to fetch remote context documents (either via `"@context": "https://example.com/context.json"` or via `@import` within an existing `@context`), is there a mechanism for disabling this feature? It seems that `JsonLdOptions.setDocumentLoader(null)` may work for that.

The use case I have in mind is an LDP server that accepts JSON-LD documents but which (for security reasons) does not wish to fetch arbitrary remote resources.

**Comment by filip26** [comment]
that's an interesting question. Thanks. Setting document loader to null is tricky, it causes `JsonLdError` with error code `LOADING_DOCUMENT_FAILED`. To avoid that you can implement something like dummy/mock loader that always returns an empty `JsonObject` but in this case you might not get the right result after processing because of the missing context.  You can also pre-process a document with a loader that just collects required imports and fetch the imports outside LDP later.

Let me know if there is a solution that works for you. A dry-run mode collecting all linked documents to fetch seems to be doable as a feature.

**Comment by acoburn** [comment]
In this case, I don't mind handling an exception (either way, I would want the response to be mapped to some sort of 4xx error to an LDP client), so the `LOADING_DOCUMENT_FAILED` error would be entirely workable. Basically, for uploaded JSON-LD documents, I want to put the responsibility on a client to embed the required context.
Thanks for the response

**Comment by acoburn** [comment]
This suggestion works for me. Thanks again

**Comment by filip26** [comment]
You are welcome. Just an idea. A server might require JSON-LD in an expanded form, that solves the issue with loading remote documents on server side and makes the contract between a server and a client more transparent + you don't need to have JSON-LD processor on a server but client.
